name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Chỉ chạy khi push lên nhánh main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      # 2. Log in to Docker Hub using single secret
      - name: Log in to Docker Hub
        run: |
          # Tách username và password từ secret GITHUBACTIONSECRET
          USERNAME=$(echo "${{ secrets.GITHUBACTIONSECRET }}" | cut -d':' -f1)
          PASSWORD=$(echo "${{ secrets.GITHUBACTIONSECRET }}" | cut -d':' -f2)
          
          echo "$PASSWORD" | docker login --username "$USERNAME" --password-stdin

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t letoanban/social-app:latest .

      # 4. Push Docker image
      - name: Push Docker image
        run: |
          docker push letoanban/social-app:latest
